# Generated by Django 3.1 on 2020-08-29 15:12

import Core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line1', models.CharField(max_length=40, verbose_name='Address Line 1')),
                ('address_line2', models.CharField(blank=True, max_length=40, verbose_name='Address Line 2')),
                ('postal_code', models.CharField(max_length=10, verbose_name='Postal Code')),
                ('city', models.CharField(max_length=40)),
                ('state_province', models.CharField(blank=True, max_length=40, verbose_name='State/Province')),
                ('longitude', models.DecimalField(decimal_places=5, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('iso_code', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'ordering': ['name', 'iso_code'],
            },
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=120)),
                ('short_code', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='StateProvince',
            fields=[
                ('iso_code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.country')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=500)),
                ('reviews_count', models.IntegerField()),
                ('rating_average', models.DecimalField(decimal_places=1, max_digits=2)),
                ('url', models.URLField()),
                ('avatar', models.ImageField(null=True, upload_to=Core.models.avatar_image_file_path)),
                ('address', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Core.address')),
                ('provide_services', models.ManyToManyField(to='Core.ServiceType')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.country'),
        ),
    ]
