# Generated by Django 3.1 on 2020-08-30 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_auto_20200829_2212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='provide_services',
        ),
        migrations.CreateModel(
            name='ServiceRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.profile')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.servicetype')),
            ],
        ),
    ]
