# Generated by Django 3.1 on 2020-08-30 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_auto_20200830_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerate',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_rates', to='Core.profile'),
        ),
    ]
