# Generated by Django 3.1 on 2020-08-30 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0007_auto_20200830_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerate',
            name='service_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_rates', to='Core.servicetype'),
        ),
    ]
