# Generated by Django 3.1 on 2020-08-31 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0008_auto_20200831_0102'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='servicerate',
            unique_together={('service_type', 'profile')},
        ),
    ]
