# Generated by Django 3.1 on 2020-08-31 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0009_auto_20200831_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerate',
            name='currency',
            field=models.CharField(blank=True, default='USD', max_length=3, null=True),
        ),
    ]
