# Generated by Django 3.1 on 2020-08-31 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0010_servicerate_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
