# Generated by Django 3.1 on 2020-08-31 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0011_servicerate_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=120)),
                ('short_code', models.CharField(max_length=20)),
                ('icon_url', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='pet_types',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='Core.PetType'),
        ),
    ]
