# Generated by Django 3.1 on 2020-08-31 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0012_auto_20200831_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pet_num',
            field=models.SmallIntegerField(default=1, null=True),
        ),
    ]
