# Generated by Django 3.1 on 2020-09-01 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0013_profile_pet_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='pettype',
            name='icon_url',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
    ]
