# Generated by Django 3.1 on 2020-09-01 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0015_auto_20200901_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='rating_average',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='reviews_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
